test

diff --git a/.github/workflows/zap.yaml b/.github/workflows/zap.yaml
--- a/.github/workflows/zap.yaml
+++ b/.github/workflows/zap.yaml
@@ -12,8 +12,35 @@ on:
   workflow_dispatch:  # Manual trigger
 
 jobs:
-  zap_scan:
+  zap_scan_main:
     runs-on: self-hosted
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v5
+        with:
+          ref: main
+
+      - name: run owasp juice shop on port 3000
+        run: |
+          docker run -d -p 127.0.0.1:3000:3000 bkimminich/juice-shop
+          echo "Waiting for main branch web app..."
+          until curl -sSf http://localhost:${{ env.WEB_APP_HOST_PORT }}; do sleep 5; done
+          echo "Main branch web app is ready"
+
+      - name: ZAP Scan
+        uses: zaproxy/action-baseline@master
+        with:
+          token: ${{ secrets.GH_BOT_TOKEN }}
+          target: 'https://www.zaproxy.org/'
+          rules_file_name: '.github/workflows/rules.tsv'
+        
+      - name: Delete web app
+        run: |
+          docker rm -f my-web-app-main || echo "Docker image for Main branch not found"
+          docker rmi my-web-app-main:latest || true
+          echo "Main branch web app deleted"
+  zap_scan:
+    runs-on: self-hosted2
 
     env:
       WEB_APP_HOST_PORT: 3000
